import fs from "node:fs";
import path from "node:path";
import type { NonLabTest, NonLabTestCategory } from "./nonlabtests";
import type {
  HomeHero,
  HomeFeature,
  HomeMostBookedCheckups,
} from "./homepages";
import type { FeaturedTestCard } from "@/components/home/FeaturedTestsSlider";
import type { HealthCheckupCard } from "@/components/home/HealthCheckupSlider";
import type { FaqItem } from "@/components/home/FaqSection";
import type { VisitCenter } from "@/components/home/ContactFormSection";

/**
 * Per-page data loader.
 *
 * Page content lives as one self-contained JSON file per route under
 * `data/allpages/<route>/page.json` (generated by `scripts/build-allpages.mjs`,
 * mirroring the public URL). A page renders by importing "its" file — so the
 * route folder structure is the single source of truth for what each page shows.
 */
const CITY = "bangalore";
const ROOT = path.join(process.cwd(), "data", "allpages");

/** Read the page.json for a route (e.g. "bangalore/ct-scan/brain-ct-scan"). */
export function getPageData<T = unknown>(route: string): T | null {
  const clean = route.replace(/^\/+|\/+$/g, "");
  const file = clean.length
    ? path.join(ROOT, clean, "page.json")
    : path.join(ROOT, "page.json");
  try {
    return JSON.parse(fs.readFileSync(file, "utf8")) as T;
  } catch {
    return null;
  }
}

export interface PageManifestEntry {
  route: string;
  type: string;
}

/** Every generated route + its page type (from the build manifest). */
export function getAllPageRoutes(): PageManifestEntry[] {
  try {
    const raw = fs.readFileSync(path.join(ROOT, "_manifest.json"), "utf8");
    return (JSON.parse(raw) as { pages: PageManifestEntry[] }).pages;
  } catch {
    return [];
  }
}

// ---- scan (non-lab) page shapes -----------------------------------------
export interface ScanDetailPageData {
  type: "scan-detail";
  route: string;
  familyPath: string;
  slug: string;
  test: NonLabTest;
  category: NonLabTestCategory | null;
  relatedTests: NonLabTest[];
}

export interface ScanListingPageData {
  type: "scan-listing";
  route: string;
  familyPath: string;
  category: NonLabTestCategory;
  tests: NonLabTest[];
}

export function getScanDetailPage(
  family: string,
  slug: string,
): ScanDetailPageData | null {
  return getPageData<ScanDetailPageData>(`${CITY}/${family}/${slug}`);
}

export function getScanListingPage(
  family: string,
): ScanListingPageData | null {
  return getPageData<ScanListingPageData>(`${CITY}/${family}`);
}

// ---- home page shape -----------------------------------------------------
export interface HomePageData {
  type: "home";
  route: "/";
  hero: HomeHero;
  features: HomeFeature[];
  featuredTests: { title: string; cards: FeaturedTestCard[] };
  mostBookedCheckups: HomeMostBookedCheckups;
  banner: string[];
  healthMonitoring: { title: string; cards: HealthCheckupCard[] };
  vitalOrgans: {
    title: string;
    description: string;
    categories: NonLabTestCategory[];
  } | null;
  faqs: FaqItem[];
  contact: {
    logo: string;
    phone?: string;
    email?: string;
    centers: VisitCenter[];
  };
}

export function getHomePage(): HomePageData | null {
  return getPageData<HomePageData>("");
}

// ---- about-us page shape -------------------------------------------------
interface IconLink {
  label: string;
  href: string;
  icon: string;
}
interface IconStat {
  value: string;
  label: string;
  icon: string;
}
interface IconText {
  icon: string;
  text: string;
}
interface IconCard {
  icon: string;
  title: string;
  body: string;
  href?: string;
}

export interface AboutUsPageData {
  type: "about-us";
  route: "/about-us";
  hero: {
    badge: string;
    title: string;
    description: string;
    buttons: IconLink[];
    stats: IconStat[];
  };
  mission: {
    overline: string;
    title: string;
    body: string[];
    highlights: IconText[];
    image: { src: string; alt: string };
    badge: { label: string; value: string; icon: string };
  };
  values: { overline: string; title: string; items: IconCard[] };
  services: {
    overline: string;
    title: string;
    labTestCount: number;
    scanCount: number;
    items: IconCard[];
  };
  milestones: {
    overline: string;
    title: string;
    items: { year: string; title: string; body: string }[];
  };
  centres: {
    overline: string;
    description: string;
    items: {
      id: string;
      name: string;
      address: string;
      phone: string;
      href: string;
    }[];
  };
  cta: {
    overline: string;
    title: string;
    description: string;
    primary: IconLink;
    call: { label: string; phone: string; icon: string };
  };
}

export function getAboutUsPage(): AboutUsPageData | null {
  return getPageData<AboutUsPageData>("about-us");
}

// ---- shared bits for static pages ---------------------------------------
interface CtaBlock {
  overline: string;
  title: string;
  description: string;
  primary: { label: string; href: string };
  call: { label: string; phone: string };
}
export interface CentreSummary {
  id: string;
  name: string;
  area: string;
  image: string;
  address: string;
  phone: string;
  email: string;
  href: string;
  weekdays: { start: string; end: string } | null;
  sunday: { start: string; end: string } | null;
}

// ---- management team -----------------------------------------------------
export interface ManagementTeamPageData {
  type: "management-team";
  route: "/management-team";
  hero: { badge: string; title: string; description: string };
  stats: { icon: string; value: string; label: string }[];
  section: { overline: string; title: string };
  members: {
    name: string;
    role: string;
    image?: string;
    description: string;
    achievements: string[];
  }[];
  cta: CtaBlock;
}
export function getManagementTeamPage(): ManagementTeamPageData | null {
  return getPageData<ManagementTeamPageData>("management-team");
}

// ---- clinical team -------------------------------------------------------
export interface ClinicalTeamPageData {
  type: "clinical-team";
  route: "/clinical-team";
  hero: { badge: string; title: string; description: string };
  stats: { icon: string; value: string; label: string }[];
  section: { overline: string; title: string };
  doctors: {
    name: string;
    qualifications: string;
    position: string;
    description: string;
    image: string;
    education: string[];
    expertise: string[];
    achievements: string[];
  }[];
  cta: CtaBlock;
}
export function getClinicalTeamPage(): ClinicalTeamPageData | null {
  return getPageData<ClinicalTeamPageData>("clinical-team");
}

// ---- contact us ----------------------------------------------------------
export interface ContactPageData {
  type: "contact-us";
  route: "/contact-us";
  overline: string;
  title: string;
  description: string;
  centres: CentreSummary[];
  contactForm: {
    logo: string;
    phone?: string;
    email?: string;
    address?: string;
  };
}
export function getContactPage(): ContactPageData | null {
  return getPageData<ContactPageData>("contact-us");
}

// ---- /bangalore landing --------------------------------------------------
export interface BangaloreLandingPageData {
  type: "bangalore-landing";
  route: "/bangalore";
  overline: string;
  title: string;
  description: string;
  servicesOverline: string;
  servicesHeading: string;
  services: { slug: string; label: string; icon: string }[];
  centres: CentreSummary[];
}
export function getBangaloreLandingPage(): BangaloreLandingPageData | null {
  return getPageData<BangaloreLandingPageData>("bangalore");
}

// ---- auth shells (login / signup) ---------------------------------------
export interface AuthPageData {
  type: "auth";
  route: string;
  overline: string;
  heading: string;
  subheading: string;
  footerText: string;
  footerLinkLabel: string;
  footerLinkHref: string;
}
export function getAuthPage(slug: "login" | "signup"): AuthPageData | null {
  return getPageData<AuthPageData>(slug);
}

// ---- policy pages --------------------------------------------------------
export interface PolicyPageData {
  type: "policy";
  route: string;
  kind: "terms" | "privacy" | "cookie" | "refund" | "legal";
  title: string;
  summary: string;
  lastUpdated: string;
  sections: { id: string; title: string; body: string }[];
}
export function getPolicyPage(slug: string): PolicyPageData | null {
  return getPageData<PolicyPageData>(slug);
}
