/**
 * Live SEO titles for blog posts, taken from the migration audit spreadsheet.
 * Used so staging blog <title>s match the live site; the root metadata template
 * appends the brand suffix, so these are the page-name part only.
 */
export const BLOG_SEO_TITLES: Record<string, string> = {
  "all-you-need-to-know-about-thyroid-scan": "Everything You Need to Know About Thyroid Scans: Steps and Interpretations",
  "breast-cancer-key-symptoms-and-common-causes": "Understanding Breast Cancer: Key Symptoms and Common Causes",
  "chest-x-ray-showing-pneumonia": "Chest X-ray Showing Pneumonia - Diagnosis & Interpretation Guide",
  "chorionic-villus-sampling-cvs-prenatal-fetal-invasive-diagnostic-test": "Chorionic Villus Sampling: Early Genetic Testing Explained",
  "complete-blood-count-test-what-is-it-and-why-do-you-need-it": "CBC Test Explained: What It Measures and Why It's Essential",
  "complete-guide-to-immunity-tests": "A Complete Guide to Immunity Tests: Understanding Your Body's Defenses",
  "comprehensive-insights-into-liver-function-assessments-importance-methodology-and-result-analysis": "Understanding Liver Function: Key Tests and Their Purpose",
  "ct-scan-and-biopsy-for-lung-cancer": "Understanding Lung Cancer CT Scans and Biopsies: Everything You Need to Know",
  "deciphering-health-understanding-your-complete-blood-count-cbc-report": "CBC Report Explained: Unlock Your Blood Test Insights",
  "diet-food-to-control-high-blood-pressure": "Top Foods to Control High Blood Pressure",
  "diet-foods-to-avoid-high-blood-pressure": "15 Foods to Avoid with High Blood Pressure",
  "difference-between-ecg-test-and-echo-test": "ECG vs. Echocardiogram: A Guide to Heart Diagnostics",
  "difference-between-mri-and-xray": "MRI vs X-Ray Scans: Differences and Similarities",
  "difference-between-pet-scans-and-ct-scans": "PET Scan vs. CT Scan: Unveiling the Differences",
  "difference-between-ultrasound-and-ct-scan": "Difference Between Ultrasound & CT Scan",
  "everything-you-need-to-know-about-malaria": "Types of Malaria: A Detailed Guide to Parasites, Symptoms, Diagnosis, and Prevention",
  "gestational-diabetes": "Understanding Gestational Diabetes: Your Guide to Causes, Diagnosis, and Management",
  "guide-to-blood-tests-for-cold-and-cough": "A Comprehensive Guide to Types of Blood Tests for Cold and Cough",
  "guide-to-eosinophilia": "Eosinophilia: Understanding Its Causes, Diagnosis, Treatment, and Ranges",
  "guide-to-fatty-liver": "What is Fatty Liver Disease?",
  "guide-to-full-body-health-checkup": "Why Full Body Checkup Is Essential When You Turn 40",
  "guide-to-gamma-glutamyl-transferase-ggt": "What level of GGT is Dangerous? A Guide to GGT Levels",
  "guide-to-high-blood-pressure": "A Comprehensive Guide to the Types, Symptoms, and Causes of High Blood Pressure",
  "guide-to-hyperthyroidism-treatment": "A Comprehensive Guide to Hyperthyroidism Treatment: From Diagnosis to Long-Term Management",
  "guide-to-ivf-understanding-the-process-costs-and-success-rates": "A Step-by-Step Guide to Understanding the IVF Process",
  "guide-to-understanding-blood-pressure": "The Ultimate Guide to Understanding Blood Pressure: Normal Ranges and Key Differences",
  "h3n2-virus-explained": "Decoding the H3N2 Virus: Key Symptoms, Diagnosis, and Prevention",
  "high-esr-in-women": "High ESR in Women: What It Means and Why It Happens",
  "how-scrotal-doppler-ultrasound-works-and-its-applications": "Scrotal Doppler Ultrasound: Diagnosis and Benefits",
  "importance-of-quadruple-marker-test-during-pregnancy": "Understanding the Quadruple Marker Test in Pregnancy",
  "influenza-a-virus-h3n2": "H3N2 Flu Cases On Rise: A Comprehensive Guide to Symptoms, Treatment, and Prevention",
  "liver-function-test-an-overview": "Liver Function Test: An Overview",
  "pelvic-ultrasound-transabdominal-method": "What to Know About Transabdominal Pelvic Ultrasound",
  "penile-doppler-ultrasound-technique-and-interpretation": "Penile Doppler Ultrasound: A Key to Male Health",
  "select-the-best-maternity-and-pregnancy-test-packages-for-healthy-and-safe-motherhood": "Trusted Pregnancy and Maternity Tests at Cadabam’s",
  "some-important-faqs-on-fetal-surgery": "Fetal Surgery: Expert FAQs and Insights",
  "the-power-of-pee-diseases-detectable-through-urine-tests": "Unlocking Health Secrets: 5 Diseases Found in Urine",
  "the-risk-factors-that-mean-you-need-a-test-for-liver-disease": "Understanding Liver Disease: Risk Factors and Testing Guide",
  "top-foods-to-include-in-your-diet-to-manage-diabetes-and-lower-blood-sugar": "Cadabam's Guide to Managing Diabetes with the Right Foods",
  "total-leucocyte-count-tlc-test": "Total Leucocyte Count (TLC) Test – Range, Process, All Details",
  "types-of-thyroid-function-tests": "Understanding Thyroid Function Tests",
  "types-of-ultrasounds": "Guide to Ultrasound Imaging: Types and Key Uses",
  "typhoid-fever-comprehensive-insights": "Typhoid Fever: Comprehensive Insights for Better Recovery",
  "ultrasound-of-scrotum": "Scrotum Ultrasound: Diagnostic Uses and Procedure",
  "understanding-anomaly-scan-during-pregnancy": "Understanding the Role of Anomaly Scans in Pregnancy",
  "understanding-blood-cancer": "Blood Cancer – Symptoms, Types, Causes, and Treatment",
  "understanding-breast-cancer-biopsy-process-results-and-more": "A Guide to Breast Cancer Biopsy and Its Results",
  "understanding-chronic-liver-disease": "Chronic Liver Disease: An Expert Guide on Causes, Symptoms and Treatment",
  "understanding-dengue-fever": "Dengue Fever Explained: Symptoms, Treatment, and When It’s Time to Worry",
  "understanding-diffusion-weighted-imaging": "Understanding Diffusion-Weighted Imaging (DWI MRI): A Comprehensive Guide",
  "understanding-effective-strategies-for-managing-uric-acid-levels": "Effective Strategies for Managing Uric Acid Levels",
  "understanding-epithelial-cells-in-urine": "Understanding Epithelial Cells in Urine",
  "understanding-fatty-liver-grades": "Fatty Liver Grade 2: Causes, Symptoms, Treatment, and Prevention",
  "understanding-fetal-doppler-scans": "All About Fetal Doppler Scans",
  "understanding-hyperglycemia-high-blood-sugar": "Hyperglycemia Symptoms, Risks, and Control Strategies",
  "understanding-hypoglycemia-low-blood-sugar": "Low Blood Sugar (Hypoglycemia): Causes, Symptoms, and Tips",
  "understanding-importance-of-tiffa-scan": "TIFFA Scan: Key to Safe Pregnancy & Fetal Health",
  "understanding-jaundice-and-its-dietary-importance": "Jaundice Diet Plan: Foods to Eat, Avoid, and Recovery Tips",
  "understanding-jaundice-causes-symptoms-and-prevention": "Is Jaundice Contagious? Causes, Symptoms & Prevention Explained",
  "understanding-jaundice-symptoms-types-and-treatment": "What Is Jaundice? Symptoms, Types, and Treatment Explained",
  "understanding-low-blood-pressure": "Low Blood Pressure: Causes, Symptoms, and Treatment Options",
  "understanding-mch-levels": "Understanding MCH Levels: Implications of Low and High Mean Corpuscular Hemoglobin in Blood Tests",
  "understanding-neonatal-jaundice-in-newborns": "Neonatal Jaundice in Newborns: What Parents and Caregivers Need to Know",
  "understanding-normal-blood-sugar-levels": "Understanding Normal Blood Sugar for Diabetes Control",
  "understanding-nuchal-translucency-scan-during-pregnancy": "What is an NT Scan during Pregnancy?",
  "understanding-platelet-count": "Platelet Count: Low vs. Normal vs. High Range in Humans",
  "understanding-postprandial-blood-sugar-ppbs": "Postprandial Blood Sugar: Key Facts and Management Tips",
  "understanding-random-blood-sugar-rbs-level-ranges": "Blood Sugar: Tests, Levels, and Management Tips",
  "understanding-rbc-normal-range": "RBC Count Normal Range: Causes, Symptoms, and Health Tips",
  "understanding-results-of-liver-function-test": "Liver Function Test Results: A Comprehensive Guide",
  "understanding-thyroid-stimulating-hormone-tsh-levels": "Thyroid Health: Understanding TSH Levels and Tests",
  "understanding-vitamin-k": "Understanding Vitamin K: Key Functions, Food Sources, and Deficiency Signs",
  "urine-culture-test-guide": "Urine Culture: Procedure, Results, and Normal Ranges",
  "white-blood-cell-count-high-low-range": "WBC Count: Understanding Normal Ranges and Identifying Abnormal Levels",
};
